{% set version = "0.40.6" %}

package:
  name: intltool
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/gnome/sources/intltool/{{ version.split('.')[:2] | join('.') }}/intltool-{{ version }}.tar.gz
  sha256: 36cd8fe249d0cc20918b6d4583267208bf74c8d541c67a5fe63316846344f9f7
  patches:
    # Patch from https://bugs.launchpad.net/intltool/+bug/1490906
    # Avoids warnings in perl 5.22 which became errors in 5.26
    - intltool-perl-5.22.patch
    # Remove the -w from shebangs; conda turns this into
    # "/usr/bin/env perl -w" which looks for an executable named "perl -w".
    - remove-w.patch

build:
  number: 3
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  host:
    - perl
    - perl-xml-parser
  run:
    - perl
    - perl-xml-parser
    - gettext

test:
  commands:
    - intltool-update --help

about:
  home: http://www.gtk.org/
  license: LGPL-2.0
  license_file: COPYING
  summary: 'Internationalization Tool Collection.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
    - dougalsutherland
    - scopatz
